import {
  parseStructFields,
  parseStructValue,
  stripQuotes,
  unwrapParens,
} from "./properties";
import type { LinkedPinRef, Pin, PinDirection, PinTypeInfo } from "./types";

const PIN_LINE_RE = /^\s*CustomProperties\s+Pin\s*\((.*)\)\s*$/i;

function parseDirection(raw: string | undefined): PinDirection {
  if (!raw) return "input";
  const v = stripQuotes(raw);
  return v === "EGPD_Output" ? "output" : "input";
}

function parseLinkedTo(raw: string | undefined): LinkedPinRef[] {
  if (!raw) return [];
  const inner = unwrapParens(raw);
  if (!inner.trim()) return [];
  const refs: LinkedPinRef[] = [];
  let i = 0;
  while (i < inner.length) {
    const { value, end } = parseStructValue(inner, i);
    i = end + 1; // skip comma
    const item = value.trim();
    if (!item) continue;
    // item looks like: NodeName <pinId>
    // NodeName may be a class-qualified ref like K2Node_CallFunction'"Name"'
    const spaceIdx = lastTopLevelSpace(item);
    if (spaceIdx === -1) {
      refs.push({ nodeName: item, pinId: "" });
      continue;
    }
    const nodePart = item.slice(0, spaceIdx).trim();
    const pinId = item.slice(spaceIdx + 1).trim();
    refs.push({ nodeName: extractNodeName(nodePart), pinId });
  }
  return refs;
}

function lastTopLevelSpace(s: string): number {
  let depth = 0;
  let inDouble = false;
  let inSingle = false;
  let last = -1;
  for (let i = 0; i < s.length; i++) {
    const c = s[i];
    if (inDouble) {
      if (c === '"') inDouble = false;
      continue;
    }
    if (inSingle) {
      if (c === "'") inSingle = false;
      continue;
    }
    if (c === '"') inDouble = true;
    else if (c === "'") inSingle = true;
    else if (c === "(") depth++;
    else if (c === ")") depth--;
    else if (c === " " && depth === 0) last = i;
  }
  return last;
}

function extractNodeName(nodeRef: string): string {
  // Forms we may see:
  //   K2Node_CallFunction_0
  //   K2Node_CallFunction'"K2Node_CallFunction_0"'
  //   /Script/BlueprintGraph.K2Node_CallFunction'K2Node_CallFunction_0'
  const quoted = nodeRef.match(/['"]([^'"]+)['"]/);
  if (quoted) return quoted[1];
  return nodeRef;
}

function buildPinType(fields: Record<string, string>): PinTypeInfo {
  const cat = stripQuotes(fields["PinType.PinCategory"] ?? "");
  const subCat = stripQuotes(fields["PinType.PinSubCategory"] ?? "");
  const subObj = stripQuotes(fields["PinType.PinSubCategoryObject"] ?? "");
  const container = stripQuotes(fields["PinType.ContainerType"] ?? "");
  const isRef = stripQuotes(fields["PinType.bIsReference"] ?? "False") === "True";
  return {
    category: cat,
    subCategory: subCat || undefined,
    subCategoryObject:
      subObj && subObj !== "None" ? extractNodeName(subObj) : undefined,
    isArray: container === "Array",
    isMap: container === "Map",
    isSet: container === "Set",
    isReference: isRef,
  };
}

export function parsePinLine(line: string): Pin | null {
  const m = line.match(PIN_LINE_RE);
  if (!m) return null;
  const inner = m[1];
  const fields = parseStructFields(inner);
  const id = stripQuotes(fields.PinId ?? "");
  const name = stripQuotes(fields.PinName ?? "");
  if (!id) return null;
  return {
    id,
    name,
    friendlyName: fields.PinFriendlyName
      ? extractLocText(fields.PinFriendlyName)
      : undefined,
    direction: parseDirection(fields.Direction),
    type: buildPinType(fields),
    defaultValue: fields.DefaultValue ? stripQuotes(fields.DefaultValue) : undefined,
    autogeneratedDefault: fields.AutogeneratedDefaultValue
      ? stripQuotes(fields.AutogeneratedDefaultValue)
      : undefined,
    linkedTo: parseLinkedTo(fields.LinkedTo),
  };
}

function extractLocText(raw: string): string | undefined {
  // NSLOCTEXT("ns", "key", "actual text")
  const m = raw.match(/NSLOCTEXT\s*\(\s*"[^"]*"\s*,\s*"[^"]*"\s*,\s*"([^"]*)"\s*\)/i);
  if (m) return m[1] || undefined;
  const lt = raw.match(/LOCTEXT\s*\(\s*"[^"]*"\s*,\s*"([^"]*)"\s*\)/i);
  if (lt) return lt[1] || undefined;
  return stripQuotes(raw) || undefined;
}
