export type PinDirection = "input" | "output";

export interface PinTypeInfo {
  category: string;
  subCategory?: string;
  subCategoryObject?: string;
  isReference?: boolean;
  isArray?: boolean;
  isMap?: boolean;
  isSet?: boolean;
}

export interface LinkedPinRef {
  nodeName: string;
  pinId: string;
}

export interface Pin {
  id: string;
  name: string;
  friendlyName?: string;
  direction: PinDirection;
  type: PinTypeInfo;
  defaultValue?: string;
  autogeneratedDefault?: string;
  linkedTo: LinkedPinRef[];
}

export interface T3DNode {
  name: string;
  className: string;
  properties: Record<string, string>;
  pins: Pin[];
  subObjects: T3DNode[];
  raw: string;
}

export interface Edge {
  from: { nodeName: string; pinId: string; pinName: string };
  to: { nodeName: string; pinId: string; pinName: string };
}

export type GraphKind = "blueprint" | "material" | "unknown";

export interface ParsedGraph {
  kind: GraphKind;
  nodes: T3DNode[];
  edges: Edge[];
  warnings: string[];
}
