import type {
  Edge,
  MacroFunctionDefinition,
  ParsedGraph,
  Pin,
  T3DNode,
} from "../parser/types";
import { parseStructFields, stripQuotes, unwrapParens } from "../parser/properties";
import { formatBlueprintNode, isExecPin, shortClassName } from "./nodeFormatters/blueprint";
import { exprFriendlyName, formatMaterialExpression } from "./nodeFormatters/material";

interface GraphIndex {
  nodes: Map<string, T3DNode>;
  // incoming edges per pinId of the receiving node
  incomingByPin: Map<string, Edge[]>;
  // outgoing edges per pinId of the sending node
  outgoingByPin: Map<string, Edge[]>;
  // nodes that have any incoming exec
  nodesWithIncomingExec: Set<string>;
}

function indexGraph(graph: ParsedGraph): GraphIndex {
  const nodes = new Map<string, T3DNode>();
  for (const n of graph.nodes) nodes.set(n.name, n);
  const incomingByPin = new Map<string, Edge[]>();
  const outgoingByPin = new Map<string, Edge[]>();
  const nodesWithIncomingExec = new Set<string>();
  for (const e of graph.edges) {
    const inKey = e.to.pinId;
    const outKey = e.from.pinId;
    if (!incomingByPin.has(inKey)) incomingByPin.set(inKey, []);
    if (!outgoingByPin.has(outKey)) outgoingByPin.set(outKey, []);
    incomingByPin.get(inKey)!.push(e);
    outgoingByPin.get(outKey)!.push(e);
    const fromNode = nodes.get(e.from.nodeName);
    const fromPin = fromNode?.pins.find((p) => p.id === e.from.pinId);
    if (fromPin && isExecPin(fromPin)) {
      nodesWithIncomingExec.add(e.to.nodeName);
    }
  }
  return { nodes, incomingByPin, outgoingByPin, nodesWithIncomingExec };
}

export function renderMarkdown(
  graph: ParsedGraph,
  definitions: MacroFunctionDefinition[] = [],
): string {
  if (graph.kind === "material") return renderMaterial(graph);
  return renderBlueprint(graph, definitions);
}

/* ------------------------------ Blueprint ------------------------------ */

function findExecRoots(graph: ParsedGraph, idx: GraphIndex): T3DNode[] {
  const roots: T3DNode[] = [];
  for (const n of graph.nodes) {
    const hasOutExec = n.pins.some((p) => isExecPin(p) && p.direction === "output");
    if (!hasOutExec) continue;
    if (idx.nodesWithIncomingExec.has(n.name)) continue;
    roots.push(n);
  }
  return roots;
}

function resolvePinInput(
  pin: Pin,
  ownerNode: T3DNode,
  idx: GraphIndex,
  visiting: Set<string>,
  dataConsumed: Set<string>,
  knownDefinitions: Set<string>,
): string {
  const incoming = idx.incomingByPin.get(pin.id) ?? [];
  if (incoming.length > 0) {
    const parts: string[] = [];
    for (const edge of incoming) {
      const src = idx.nodes.get(edge.from.nodeName);
      if (!src) {
        parts.push(`<- ${edge.from.nodeName}.${edge.from.pinName}`);
        continue;
      }
      // Don't mark a node as "shown inline" if it has its own exec flow —
      // it'll show up in an exec chain regardless and shouldn't be hidden
      // from the orphan list.
      if (!src.pins.some((p) => isExecPin(p))) {
        dataConsumed.add(src.name);
      }
      parts.push(
        renderDataExpression(
          src,
          edge.from.pinName,
          idx,
          visiting,
          knownDefinitions,
          dataConsumed,
        ),
      );
    }
    return parts.join(", ");
  }
  if (pin.defaultValue && pin.defaultValue.length > 0) {
    return formatLiteral(pin.defaultValue, pin.type.category);
  }
  if (pin.autogeneratedDefault && pin.autogeneratedDefault.length > 0) {
    return formatLiteral(pin.autogeneratedDefault, pin.type.category);
  }
  return defaultForCategory(pin.type.category);
}

function defaultForCategory(cat: string): string {
  switch (cat) {
    case "bool":
      return "false";
    case "int":
    case "int64":
    case "byte":
      return "0";
    case "float":
    case "double":
    case "real":
      return "0.0";
    case "string":
    case "name":
    case "text":
      return '""';
    case "object":
    case "class":
    case "interface":
    case "softobject":
      return "None";
    default:
      return "<unset>";
  }
}

function formatLiteral(raw: string, cat: string): string {
  const v = raw.trim();
  if (!v) return defaultForCategory(cat);
  if (cat === "string" || cat === "name" || cat === "text") {
    if (v.startsWith('"') && v.endsWith('"')) return v;
    return JSON.stringify(v);
  }
  if (cat === "struct") {
    return v;
  }
  return v;
}

function renderDataExpression(
  node: T3DNode,
  outputPinName: string,
  idx: GraphIndex,
  visiting: Set<string>,
  knownDefinitions: Set<string>,
  dataConsumed: Set<string>,
): string {
  if (visiting.has(node.name)) return node.name;
  visiting.add(node.name);
  try {
    const formatted = formatBlueprintNode(node, {
      resolveInput: (pin) =>
        resolvePinInput(pin, node, idx, visiting, dataConsumed, knownDefinitions),
      outputPinName,
      knownDefinitions,
    });
    if (formatted.expression !== undefined) return formatted.expression;
    // Default: NodeShortName.outputPin
    return `${shortClassName(node)}.${outputPinName}`;
  } finally {
    visiting.delete(node.name);
  }
}

function renderExecChain(
  start: T3DNode,
  idx: GraphIndex,
  depth: number,
  seen: Set<string>,
  warnings: string[],
  knownDefinitions: Set<string>,
  dataConsumed: Set<string>,
): string[] {
  const lines: string[] = [];
  let current: T3DNode | undefined = start;
  while (current) {
    if (seen.has(current.name)) {
      lines.push(`${"  ".repeat(depth)}- (loop back to ${current.name})`);
      break;
    }
    seen.add(current.name);
    const formatted = formatBlueprintNode(current, {
      resolveInput: (pin) =>
        resolvePinInput(
          pin,
          current!,
          idx,
          new Set(),
          dataConsumed,
          knownDefinitions,
        ),
      knownDefinitions,
    });
    if (formatted.warnings) warnings.push(...formatted.warnings);
    lines.push(`${"  ".repeat(depth)}- ${formatted.statement}`);
    // Handle branch-style nodes that fan out via multiple named exec outputs
    if (formatted.branches && formatted.branches.length > 0) {
      for (const branch of formatted.branches) {
        const outPin = current.pins.find(
          (p) => p.direction === "output" && isExecPin(p) && p.name === branch.pinName,
        );
        lines.push(`${"  ".repeat(depth + 1)}${branch.label}:`);
        if (outPin) {
          const outs = idx.outgoingByPin.get(outPin.id) ?? [];
          for (const edge of outs) {
            const next = idx.nodes.get(edge.to.nodeName);
            if (next)
              lines.push(
                ...renderExecChain(
                  next,
                  idx,
                  depth + 2,
                  seen,
                  warnings,
                  knownDefinitions,
                  dataConsumed,
                ),
              );
          }
        }
      }
      break;
    }
    // Linear continuation: follow "then" or the first output exec pin
    const nextOut =
      current.pins.find((p) => p.direction === "output" && isExecPin(p) && p.name === "then") ??
      current.pins.find((p) => p.direction === "output" && isExecPin(p));
    if (!nextOut) break;
    const outs = idx.outgoingByPin.get(nextOut.id) ?? [];
    if (outs.length === 0) break;
    const next = idx.nodes.get(outs[0].to.nodeName);
    current = next;
  }
  return lines;
}

/** Renders the inner content of a blueprint-kind graph — section bodies but
 * no top-level heading or warnings block. */
function renderBlueprintBody(
  graph: ParsedGraph,
  knownDefinitions: Set<string>,
  headingLevel: "##" | "###",
): { lines: string[]; warnings: string[] } {
  const idx = indexGraph(graph);
  const roots = findExecRoots(graph, idx);
  const runtimeWarnings: string[] = [];
  const lines: string[] = [];
  // Tracks data nodes that were inlined as expressions into an exec-chain
  // line — those don't need to re-appear in the "Data nodes" orphan list.
  const dataConsumed = new Set<string>();

  const allVisited = new Set<string>();
  for (const root of roots) {
    lines.push(`${headingLevel} ${rootHeading(root)}`);
    lines.push("");
    const chain = renderExecChain(
      root,
      idx,
      0,
      allVisited,
      runtimeWarnings,
      knownDefinitions,
      dataConsumed,
    );
    lines.push(...chain);
    lines.push("");
  }
  // Pure-data orphan section: nodes with no exec pins, not visited by any
  // exec chain, and not already inlined as a data expression upstream.
  const orphans = graph.nodes.filter(
    (n) =>
      !allVisited.has(n.name) &&
      !dataConsumed.has(n.name) &&
      !n.pins.some((p) => isExecPin(p)),
  );
  if (orphans.length > 0) {
    lines.push(`${headingLevel} Data nodes`);
    lines.push("");
    for (const n of orphans) {
      const formatted = formatBlueprintNode(n, {
        resolveInput: (pin) =>
          resolvePinInput(pin, n, idx, new Set(), dataConsumed, knownDefinitions),
        knownDefinitions,
      });
      if (formatted.warnings) runtimeWarnings.push(...formatted.warnings);
      lines.push(`- \`${n.name}\`: ${formatted.statement}`);
    }
    lines.push("");
  }
  return { lines, warnings: runtimeWarnings };
}

function renderBlueprint(
  graph: ParsedGraph,
  definitions: MacroFunctionDefinition[] = [],
): string {
  const knownDefinitions = new Set(definitions.map((d) => d.name));
  const main = renderBlueprintBody(graph, knownDefinitions, "##");

  const definitionSections: string[] = [];
  const definitionWarnings: string[] = [];
  for (const def of definitions) {
    const label = def.kind === "macro" ? "Macro" : "Function";
    definitionSections.push(`## ${label}: ${def.name}`);
    definitionSections.push("");
    if (def.graph.nodes.length === 0) {
      definitionSections.push(`*(empty paste)*`);
      definitionSections.push("");
      continue;
    }
    const sub = renderBlueprintBody(def.graph, knownDefinitions, "###");
    definitionSections.push(...sub.lines);
    definitionWarnings.push(
      ...def.graph.warnings.map((w) => `[${def.name}] ${w}`),
      ...sub.warnings.map((w) => `[${def.name}] ${w}`),
    );
  }

  const out: string[] = [];
  out.push(`# Blueprint Graph`);
  out.push("");
  const allWarnings = [
    ...graph.warnings,
    ...dedupe(main.warnings),
    ...dedupe(definitionWarnings),
  ];
  if (allWarnings.length) {
    out.push(`> Warnings:`);
    for (const w of allWarnings) out.push(`> - ${w}`);
    out.push("");
  }
  if (main.lines.length === 0) {
    out.push(`*No event/root nodes found.*`);
    out.push("");
  } else {
    out.push(...main.lines);
  }
  if (definitionSections.length > 0) {
    out.push(...definitionSections);
  }
  return out.join("\n").trim() + "\n";
}

function dedupe(items: string[]): string[] {
  return Array.from(new Set(items));
}

function rootHeading(node: T3DNode): string {
  const formatted = formatBlueprintNode(node, {
    resolveInput: () => "",
  });
  return formatted.heading ?? formatted.statement;
}

/* ------------------------------ Material ------------------------------ */

function findMaterialRoots(graph: ParsedGraph): T3DNode[] {
  return graph.nodes.filter(
    (n) =>
      n.className.includes("MaterialGraphNode_Root") ||
      n.className.includes("MaterialGraphNode_OutputResult") ||
      n.className.includes("MaterialExpressionFunctionOutput") ||
      // The wrapper sometimes carries the output as a sub-object instead.
      n.subObjects.some((s) =>
        s.className.includes("MaterialExpressionFunctionOutput"),
      ),
  );
}

function renderMaterialExpr(
  node: T3DNode,
  outputName: string | undefined,
  idx: GraphIndex,
  letBindings: Map<string, string>,
  visiting: Set<string>,
): string {
  // Reuse via let bindings: if a node is referenced multiple times, hoist it.
  const refCount = countMaterialRefs(node.name, idx);
  if (refCount > 1 && letBindings.has(node.name)) {
    return letBindings.get(node.name)!;
  }
  if (visiting.has(node.name)) return node.name;
  visiting.add(node.name);
  try {
    const resolved = formatMaterialExpression(node, (pinName) => {
      const pin = node.pins.find((p) => p.direction === "input" && p.name === pinName);
      if (!pin) return undefined;
      const incoming = idx.incomingByPin.get(pin.id) ?? [];
      if (incoming.length === 0) {
        if (pin.defaultValue) return pin.defaultValue;
        return undefined;
      }
      const edge = incoming[0];
      const src = idx.nodes.get(edge.from.nodeName);
      if (!src) return `<-${edge.from.nodeName}`;
      return renderMaterialExpr(src, edge.from.pinName, idx, letBindings, visiting);
    });
    const expr = resolved ?? `${exprFriendlyName(node)}()`;
    if (refCount > 1) {
      const letName = `expr_${letBindings.size + 1}_${exprFriendlyName(node)}`;
      letBindings.set(node.name, letName);
      return letName;
    }
    return expr;
  } finally {
    visiting.delete(node.name);
  }
}

function countMaterialRefs(nodeName: string, idx: GraphIndex): number {
  let count = 0;
  for (const edges of idx.outgoingByPin.values()) {
    for (const e of edges) if (e.from.nodeName === nodeName) count++;
  }
  return count;
}

function renderMaterial(graph: ParsedGraph): string {
  const idx = indexGraph(graph);
  const roots = findMaterialRoots(graph);
  const out: string[] = [];
  out.push(`# Material Graph`);
  out.push("");
  if (graph.warnings.length) {
    out.push(`> Warnings:`);
    for (const w of graph.warnings) out.push(`> - ${w}`);
    out.push("");
  }
  if (roots.length === 0) {
    // Walk from terminal nodes (those with no outgoing edges) instead
    const terminals = graph.nodes.filter((n) => {
      const outs = n.pins.filter((p) => p.direction === "output");
      return outs.every((p) => (idx.outgoingByPin.get(p.id) ?? []).length === 0);
    });
    for (const t of terminals) {
      const expr = renderMaterialExpr(t, undefined, idx, new Map(), new Set());
      out.push(`- \`${exprFriendlyName(t)}\` = ${expr}`);
    }
    out.push("");
    return out.join("\n").trim() + "\n";
  }
  for (const root of roots) {
    const letBindings = new Map<string, string>();
    const lines: string[] = [];
    // Material output: each input pin is a named output channel (BaseColor, Metallic, etc.)
    for (const pin of root.pins.filter((p) => p.direction === "input")) {
      const incoming = idx.incomingByPin.get(pin.id) ?? [];
      if (incoming.length === 0) continue;
      const edge = incoming[0];
      const src = idx.nodes.get(edge.from.nodeName);
      if (!src) continue;
      const expr = renderMaterialExpr(src, edge.from.pinName, idx, letBindings, new Set());
      lines.push(`${pin.name} = ${expr}`);
    }
    if (letBindings.size > 0) {
      out.push("```");
      for (const [nodeName, varName] of letBindings) {
        const node = idx.nodes.get(nodeName);
        if (!node) continue;
        const expr = formatMaterialExpression(node, (pinName) => {
          const p = node.pins.find((q) => q.direction === "input" && q.name === pinName);
          if (!p) return undefined;
          const incoming = idx.incomingByPin.get(p.id) ?? [];
          if (incoming.length === 0) return p.defaultValue;
          const edge = incoming[0];
          const src2 = idx.nodes.get(edge.from.nodeName);
          if (!src2) return undefined;
          if (letBindings.has(src2.name)) return letBindings.get(src2.name);
          return renderMaterialExpr(src2, edge.from.pinName, idx, letBindings, new Set());
        });
        out.push(`let ${varName} = ${expr ?? exprFriendlyName(node) + "()"};`);
      }
      out.push("");
      for (const l of lines) out.push(l);
      out.push("```");
    } else {
      out.push("```");
      for (const l of lines) out.push(l);
      out.push("```");
    }
    out.push("");
  }
  return out.join("\n").trim() + "\n";
}

/* exports for parser-side helpers used by node formatters */
export { parseStructFields, stripQuotes, unwrapParens };
