import type { Edge, ParsedGraph, Pin, T3DNode } from "../parser/types";
import { parseStructFields, stripQuotes, unwrapParens } from "../parser/properties";
import { formatBlueprintNode, isExecPin, shortClassName } from "./nodeFormatters/blueprint";
import { formatMaterialExpression } from "./nodeFormatters/material";

interface GraphIndex {
  nodes: Map<string, T3DNode>;
  // incoming edges per pinId of the receiving node
  incomingByPin: Map<string, Edge[]>;
  // outgoing edges per pinId of the sending node
  outgoingByPin: Map<string, Edge[]>;
  // nodes that have any incoming exec
  nodesWithIncomingExec: Set<string>;
}

function indexGraph(graph: ParsedGraph): GraphIndex {
  const nodes = new Map<string, T3DNode>();
  for (const n of graph.nodes) nodes.set(n.name, n);
  const incomingByPin = new Map<string, Edge[]>();
  const outgoingByPin = new Map<string, Edge[]>();
  const nodesWithIncomingExec = new Set<string>();
  for (const e of graph.edges) {
    const inKey = e.to.pinId;
    const outKey = e.from.pinId;
    if (!incomingByPin.has(inKey)) incomingByPin.set(inKey, []);
    if (!outgoingByPin.has(outKey)) outgoingByPin.set(outKey, []);
    incomingByPin.get(inKey)!.push(e);
    outgoingByPin.get(outKey)!.push(e);
    const fromNode = nodes.get(e.from.nodeName);
    const fromPin = fromNode?.pins.find((p) => p.id === e.from.pinId);
    if (fromPin && isExecPin(fromPin)) {
      nodesWithIncomingExec.add(e.to.nodeName);
    }
  }
  return { nodes, incomingByPin, outgoingByPin, nodesWithIncomingExec };
}

export function renderMarkdown(graph: ParsedGraph): string {
  if (graph.kind === "material") return renderMaterial(graph);
  return renderBlueprint(graph);
}

/* ------------------------------ Blueprint ------------------------------ */

const EVENT_CLASSES = [
  "K2Node_Event",
  "K2Node_CustomEvent",
  "K2Node_FunctionEntry",
  "K2Node_Tunnel",
  "K2Node_InputAction",
  "K2Node_InputKey",
  "K2Node_InputAxisEvent",
  "K2Node_ComponentBoundEvent",
  "K2Node_ActorBoundEvent",
];

function isEventClass(className: string): boolean {
  return EVENT_CLASSES.some((c) => className.includes(c));
}

function findExecRoots(graph: ParsedGraph, idx: GraphIndex): T3DNode[] {
  const roots: T3DNode[] = [];
  for (const n of graph.nodes) {
    if (isEventClass(n.className)) {
      roots.push(n);
      continue;
    }
    // Node has an output exec pin but no incoming exec edges
    const hasOutExec = n.pins.some((p) => isExecPin(p) && p.direction === "output");
    if (hasOutExec && !idx.nodesWithIncomingExec.has(n.name)) {
      // skip pure utility nodes already attached as roots (events handled above)
      roots.push(n);
    }
  }
  return roots;
}

function resolvePinInput(
  pin: Pin,
  ownerNode: T3DNode,
  idx: GraphIndex,
  visiting: Set<string>,
): string {
  const incoming = idx.incomingByPin.get(pin.id) ?? [];
  if (incoming.length > 0) {
    const parts: string[] = [];
    for (const edge of incoming) {
      const src = idx.nodes.get(edge.from.nodeName);
      if (!src) {
        parts.push(`<- ${edge.from.nodeName}.${edge.from.pinName}`);
        continue;
      }
      // Render the upstream value as an inline expression
      parts.push(renderDataExpression(src, edge.from.pinName, idx, visiting));
    }
    return parts.join(", ");
  }
  if (pin.defaultValue && pin.defaultValue.length > 0) {
    return formatLiteral(pin.defaultValue, pin.type.category);
  }
  if (pin.autogeneratedDefault && pin.autogeneratedDefault.length > 0) {
    return formatLiteral(pin.autogeneratedDefault, pin.type.category);
  }
  return defaultForCategory(pin.type.category);
}

function defaultForCategory(cat: string): string {
  switch (cat) {
    case "bool":
      return "false";
    case "int":
    case "int64":
    case "byte":
      return "0";
    case "float":
    case "double":
    case "real":
      return "0.0";
    case "string":
    case "name":
    case "text":
      return '""';
    case "object":
    case "class":
    case "interface":
    case "softobject":
      return "None";
    default:
      return "<unset>";
  }
}

function formatLiteral(raw: string, cat: string): string {
  const v = raw.trim();
  if (!v) return defaultForCategory(cat);
  if (cat === "string" || cat === "name" || cat === "text") {
    if (v.startsWith('"') && v.endsWith('"')) return v;
    return JSON.stringify(v);
  }
  if (cat === "struct") {
    return v;
  }
  return v;
}

function renderDataExpression(
  node: T3DNode,
  outputPinName: string,
  idx: GraphIndex,
  visiting: Set<string>,
): string {
  if (visiting.has(node.name)) return node.name;
  visiting.add(node.name);
  try {
    const formatted = formatBlueprintNode(node, {
      resolveInput: (pin) => resolvePinInput(pin, node, idx, visiting),
      outputPinName,
    });
    if (formatted.expression !== undefined) return formatted.expression;
    // Default: NodeShortName.outputPin
    return `${shortClassName(node)}.${outputPinName}`;
  } finally {
    visiting.delete(node.name);
  }
}

function renderExecChain(
  start: T3DNode,
  idx: GraphIndex,
  depth: number,
  seen: Set<string>,
): string[] {
  const lines: string[] = [];
  let current: T3DNode | undefined = start;
  while (current) {
    if (seen.has(current.name)) {
      lines.push(`${"  ".repeat(depth)}- (loop back to ${current.name})`);
      break;
    }
    seen.add(current.name);
    const formatted = formatBlueprintNode(current, {
      resolveInput: (pin) => resolvePinInput(pin, current!, idx, new Set()),
    });
    lines.push(`${"  ".repeat(depth)}- ${formatted.statement}`);
    // Handle branch-style nodes that fan out via multiple named exec outputs
    if (formatted.branches && formatted.branches.length > 0) {
      for (const branch of formatted.branches) {
        const outPin = current.pins.find(
          (p) => p.direction === "output" && isExecPin(p) && p.name === branch.pinName,
        );
        lines.push(`${"  ".repeat(depth + 1)}${branch.label}:`);
        if (outPin) {
          const outs = idx.outgoingByPin.get(outPin.id) ?? [];
          for (const edge of outs) {
            const next = idx.nodes.get(edge.to.nodeName);
            if (next) lines.push(...renderExecChain(next, idx, depth + 2, seen));
          }
        }
      }
      break;
    }
    // Linear continuation: follow "then" or the first output exec pin
    const nextOut =
      current.pins.find((p) => p.direction === "output" && isExecPin(p) && p.name === "then") ??
      current.pins.find((p) => p.direction === "output" && isExecPin(p));
    if (!nextOut) break;
    const outs = idx.outgoingByPin.get(nextOut.id) ?? [];
    if (outs.length === 0) break;
    const next = idx.nodes.get(outs[0].to.nodeName);
    current = next;
  }
  return lines;
}

function renderBlueprint(graph: ParsedGraph): string {
  const idx = indexGraph(graph);
  const roots = findExecRoots(graph, idx);
  const out: string[] = [];
  out.push(`# Blueprint Graph`);
  out.push("");
  if (graph.warnings.length) {
    out.push(`> Warnings:`);
    for (const w of graph.warnings) out.push(`> - ${w}`);
    out.push("");
  }
  if (roots.length === 0) {
    out.push(`*No event/root nodes found.*`);
    out.push("");
  }
  const allVisited = new Set<string>();
  for (const root of roots) {
    out.push(`## ${rootHeading(root)}`);
    out.push("");
    const chain = renderExecChain(root, idx, 0, allVisited);
    out.push(...chain);
    out.push("");
  }
  // Orphan data nodes (no exec, not visited)
  const orphans = graph.nodes.filter(
    (n) => !allVisited.has(n.name) && !n.pins.some((p) => isExecPin(p)),
  );
  if (orphans.length > 0) {
    out.push(`## Data nodes`);
    out.push("");
    for (const n of orphans) {
      const formatted = formatBlueprintNode(n, {
        resolveInput: (pin) => resolvePinInput(pin, n, idx, new Set()),
      });
      out.push(`- \`${n.name}\`: ${formatted.statement}`);
    }
    out.push("");
  }
  return out.join("\n").trim() + "\n";
}

function rootHeading(node: T3DNode): string {
  const formatted = formatBlueprintNode(node, {
    resolveInput: () => "",
  });
  return formatted.heading ?? formatted.statement;
}

/* ------------------------------ Material ------------------------------ */

function findMaterialRoots(graph: ParsedGraph): T3DNode[] {
  return graph.nodes.filter(
    (n) =>
      n.className.includes("MaterialGraphNode_Root") ||
      n.className.includes("MaterialExpressionFunctionOutput"),
  );
}

function renderMaterialExpr(
  node: T3DNode,
  outputName: string | undefined,
  idx: GraphIndex,
  letBindings: Map<string, string>,
  visiting: Set<string>,
): string {
  // Reuse via let bindings: if a node is referenced multiple times, hoist it.
  const refCount = countMaterialRefs(node.name, idx);
  if (refCount > 1 && letBindings.has(node.name)) {
    return letBindings.get(node.name)!;
  }
  if (visiting.has(node.name)) return node.name;
  visiting.add(node.name);
  try {
    const resolved = formatMaterialExpression(node, (pinName) => {
      const pin = node.pins.find((p) => p.direction === "input" && p.name === pinName);
      if (!pin) return undefined;
      const incoming = idx.incomingByPin.get(pin.id) ?? [];
      if (incoming.length === 0) {
        if (pin.defaultValue) return pin.defaultValue;
        return undefined;
      }
      const edge = incoming[0];
      const src = idx.nodes.get(edge.from.nodeName);
      if (!src) return `<-${edge.from.nodeName}`;
      return renderMaterialExpr(src, edge.from.pinName, idx, letBindings, visiting);
    });
    const expr = resolved ?? `${shortClassName(node)}()`;
    if (refCount > 1) {
      const letName = `expr_${letBindings.size + 1}_${shortClassName(node)}`;
      letBindings.set(node.name, letName);
      return letName;
    }
    return expr;
  } finally {
    visiting.delete(node.name);
  }
}

function countMaterialRefs(nodeName: string, idx: GraphIndex): number {
  let count = 0;
  for (const edges of idx.outgoingByPin.values()) {
    for (const e of edges) if (e.from.nodeName === nodeName) count++;
  }
  return count;
}

function renderMaterial(graph: ParsedGraph): string {
  const idx = indexGraph(graph);
  const roots = findMaterialRoots(graph);
  const out: string[] = [];
  out.push(`# Material Graph`);
  out.push("");
  if (graph.warnings.length) {
    out.push(`> Warnings:`);
    for (const w of graph.warnings) out.push(`> - ${w}`);
    out.push("");
  }
  if (roots.length === 0) {
    // Walk from terminal nodes (those with no outgoing edges) instead
    const terminals = graph.nodes.filter((n) => {
      const outs = n.pins.filter((p) => p.direction === "output");
      return outs.every((p) => (idx.outgoingByPin.get(p.id) ?? []).length === 0);
    });
    for (const t of terminals) {
      const expr = renderMaterialExpr(t, undefined, idx, new Map(), new Set());
      out.push(`- \`${shortClassName(t)}\` = ${expr}`);
    }
    out.push("");
    return out.join("\n").trim() + "\n";
  }
  for (const root of roots) {
    const letBindings = new Map<string, string>();
    const lines: string[] = [];
    // Material output: each input pin is a named output channel (BaseColor, Metallic, etc.)
    for (const pin of root.pins.filter((p) => p.direction === "input")) {
      const incoming = idx.incomingByPin.get(pin.id) ?? [];
      if (incoming.length === 0) continue;
      const edge = incoming[0];
      const src = idx.nodes.get(edge.from.nodeName);
      if (!src) continue;
      const expr = renderMaterialExpr(src, edge.from.pinName, idx, letBindings, new Set());
      lines.push(`${pin.name} = ${expr}`);
    }
    if (letBindings.size > 0) {
      out.push("```");
      for (const [nodeName, varName] of letBindings) {
        const node = idx.nodes.get(nodeName);
        if (!node) continue;
        const expr = formatMaterialExpression(node, (pinName) => {
          const p = node.pins.find((q) => q.direction === "input" && q.name === pinName);
          if (!p) return undefined;
          const incoming = idx.incomingByPin.get(p.id) ?? [];
          if (incoming.length === 0) return p.defaultValue;
          const edge = incoming[0];
          const src2 = idx.nodes.get(edge.from.nodeName);
          if (!src2) return undefined;
          if (letBindings.has(src2.name)) return letBindings.get(src2.name);
          return renderMaterialExpr(src2, edge.from.pinName, idx, letBindings, new Set());
        });
        out.push(`let ${varName} = ${expr ?? shortClassName(node) + "()"};`);
      }
      out.push("");
      for (const l of lines) out.push(l);
      out.push("```");
    } else {
      out.push("```");
      for (const l of lines) out.push(l);
      out.push("```");
    }
    out.push("");
  }
  return out.join("\n").trim() + "\n";
}

/* exports for parser-side helpers used by node formatters */
export { parseStructFields, stripQuotes, unwrapParens };
