import YAML from "yaml";
import type {
  MacroFunctionDefinition,
  ParsedGraph,
  Pin,
  T3DNode,
} from "../parser/types";

interface SerializedPin {
  id: string;
  name: string;
  friendlyName?: string;
  direction: Pin["direction"];
  type: Pin["type"];
  defaultValue?: string;
  autogeneratedDefault?: string;
  linkedTo: { node: string; pinId: string }[];
}

interface SerializedNode {
  id: string;
  class: string;
  properties: Record<string, string>;
  pins: SerializedPin[];
  subObjects?: SerializedNode[];
  raw: string;
}

interface SerializedDefinition {
  name: string;
  kind: "macro" | "function";
  nodes: SerializedNode[];
  edges: ParsedGraph["edges"];
  warnings: string[];
}

interface SerializedGraph {
  kind: ParsedGraph["kind"];
  warnings: string[];
  nodes: SerializedNode[];
  edges: ParsedGraph["edges"];
  definitions?: SerializedDefinition[];
}

function serializeNode(n: T3DNode): SerializedNode {
  return {
    id: n.name,
    class: n.className,
    properties: n.properties,
    pins: n.pins.map((p) => ({
      id: p.id,
      name: p.name,
      friendlyName: p.friendlyName,
      direction: p.direction,
      type: p.type,
      defaultValue: p.defaultValue,
      autogeneratedDefault: p.autogeneratedDefault,
      linkedTo: p.linkedTo.map((l) => ({ node: l.nodeName, pinId: l.pinId })),
    })),
    subObjects: n.subObjects.length ? n.subObjects.map(serializeNode) : undefined,
    raw: n.raw,
  };
}

export function toSerializedGraph(
  graph: ParsedGraph,
  definitions: MacroFunctionDefinition[] = [],
): SerializedGraph {
  return {
    kind: graph.kind,
    warnings: graph.warnings,
    nodes: graph.nodes.map(serializeNode),
    edges: graph.edges,
    definitions: definitions.length
      ? definitions.map((d) => ({
          name: d.name,
          kind: d.kind,
          nodes: d.graph.nodes.map(serializeNode),
          edges: d.graph.edges,
          warnings: d.graph.warnings,
        }))
      : undefined,
  };
}

export function renderYaml(
  graph: ParsedGraph,
  definitions: MacroFunctionDefinition[] = [],
): string {
  return YAML.stringify(toSerializedGraph(graph, definitions), { lineWidth: 0 });
}

export function renderJson(
  graph: ParsedGraph,
  definitions: MacroFunctionDefinition[] = [],
): string {
  return JSON.stringify(toSerializedGraph(graph, definitions), null, 2);
}
