export const EXAMPLES: { label: string; value: string }[] = [
  {
    label: "Blueprint: BeginPlay -> PrintString",
    value: `Begin Object Class=/Script/BlueprintGraph.K2Node_Event Name="K2Node_Event_0"
   EventReference=(MemberParent=Class'"/Script/Engine.Actor"',MemberName="ReceiveBeginPlay")
   bOverrideFunction=True
   NodePosX=-48
   NodePosY=128
   NodeGuid=AAAA0001000000000000000000000001
   CustomProperties Pin (PinId=11111111111111111111111111111111,PinName="OutputDelegate",PinType.PinCategory="delegate",PinType.PinSubCategory="",PinType.PinSubCategoryObject=None,PinType.ContainerType=None,PinType.bIsReference=False,Direction="EGPD_Output",LinkedTo=())
   CustomProperties Pin (PinId=22222222222222222222222222222222,PinName="then",PinType.PinCategory="exec",PinType.PinSubCategory="",PinType.PinSubCategoryObject=None,PinType.ContainerType=None,PinType.bIsReference=False,Direction="EGPD_Output",LinkedTo=(K2Node_CallFunction_0 33333333333333333333333333333333,))
End Object
Begin Object Class=/Script/BlueprintGraph.K2Node_CallFunction Name="K2Node_CallFunction_0"
   bIsPureFunc=False
   FunctionReference=(MemberParent=Class'"/Script/Engine.KismetSystemLibrary"',MemberName="PrintString")
   NodePosX=224
   NodePosY=112
   NodeGuid=AAAA0002000000000000000000000002
   CustomProperties Pin (PinId=33333333333333333333333333333333,PinName="execute",PinType.PinCategory="exec",PinType.PinSubCategory="",PinType.PinSubCategoryObject=None,PinType.ContainerType=None,PinType.bIsReference=False,LinkedTo=(K2Node_Event_0 22222222222222222222222222222222,))
   CustomProperties Pin (PinId=44444444444444444444444444444444,PinName="then",PinType.PinCategory="exec",PinType.PinSubCategory="",PinType.PinSubCategoryObject=None,PinType.ContainerType=None,PinType.bIsReference=False,Direction="EGPD_Output",LinkedTo=())
   CustomProperties Pin (PinId=55555555555555555555555555555555,PinName="WorldContextObject",PinType.PinCategory="object",PinType.PinSubCategory="",PinType.PinSubCategoryObject=Class'"/Script/CoreUObject.Object"',PinType.ContainerType=None,PinType.bIsReference=False,DefaultValue="None")
   CustomProperties Pin (PinId=66666666666666666666666666666666,PinName="InString",PinType.PinCategory="string",PinType.PinSubCategory="",PinType.PinSubCategoryObject=None,PinType.ContainerType=None,PinType.bIsReference=False,DefaultValue="Hello",AutogeneratedDefaultValue="Hello")
   CustomProperties Pin (PinId=77777777777777777777777777777777,PinName="bPrintToScreen",PinType.PinCategory="bool",PinType.PinSubCategory="",PinType.PinSubCategoryObject=None,PinType.ContainerType=None,PinType.bIsReference=False,DefaultValue="true",AutogeneratedDefaultValue="true")
End Object`,
  },
  {
    label: "Material: TextureSample * Color -> BaseColor",
    value: `Begin Object Class=/Script/Engine.MaterialExpressionTextureSampleParameter2D Name="MaterialExpressionTextureSampleParameter2D_0"
   ParameterName="BaseColorTex"
   MaterialExpressionEditorX=-352
   MaterialExpressionEditorY=0
   MaterialExpressionGuid=BBBB0001000000000000000000000001
   CustomProperties Pin (PinId=AAAA1000000000000000000000000001,PinName="UVs",PinType.PinCategory="materialinput",Direction="EGPD_Input",LinkedTo=())
   CustomProperties Pin (PinId=AAAA1000000000000000000000000002,PinName="RGB",PinType.PinCategory="materialoutput",Direction="EGPD_Output",LinkedTo=(MaterialGraphNode_Multiply_0 AAAA2000000000000000000000000001,))
End Object
Begin Object Class=/Script/Engine.MaterialExpressionMultiply Name="MaterialGraphNode_Multiply_0"
   MaterialExpressionEditorX=-128
   MaterialExpressionEditorY=0
   MaterialExpressionGuid=BBBB0002000000000000000000000002
   CustomProperties Pin (PinId=AAAA2000000000000000000000000001,PinName="A",PinType.PinCategory="materialinput",Direction="EGPD_Input",LinkedTo=(MaterialExpressionTextureSampleParameter2D_0 AAAA1000000000000000000000000002,))
   CustomProperties Pin (PinId=AAAA2000000000000000000000000002,PinName="B",PinType.PinCategory="materialinput",Direction="EGPD_Input",LinkedTo=(MaterialExpressionVectorParameter_0 AAAA3000000000000000000000000001,))
   CustomProperties Pin (PinId=AAAA2000000000000000000000000003,PinName="Output",PinType.PinCategory="materialoutput",Direction="EGPD_Output",LinkedTo=(MaterialGraphNode_Root_0 AAAA4000000000000000000000000001,))
End Object
Begin Object Class=/Script/Engine.MaterialExpressionVectorParameter Name="MaterialExpressionVectorParameter_0"
   ParameterName="Tint"
   MaterialExpressionEditorX=-352
   MaterialExpressionEditorY=128
   MaterialExpressionGuid=BBBB0003000000000000000000000003
   CustomProperties Pin (PinId=AAAA3000000000000000000000000001,PinName="RGB",PinType.PinCategory="materialoutput",Direction="EGPD_Output",LinkedTo=(MaterialGraphNode_Multiply_0 AAAA2000000000000000000000000002,))
End Object
Begin Object Class=/Script/UnrealEd.MaterialGraphNode_Root Name="MaterialGraphNode_Root_0"
   MaterialExpressionEditorX=128
   MaterialExpressionEditorY=0
   MaterialExpressionGuid=BBBB0004000000000000000000000004
   CustomProperties Pin (PinId=AAAA4000000000000000000000000001,PinName="BaseColor",PinType.PinCategory="materialinput",Direction="EGPD_Input",LinkedTo=(MaterialGraphNode_Multiply_0 AAAA2000000000000000000000000003,))
   CustomProperties Pin (PinId=AAAA4000000000000000000000000002,PinName="Metallic",PinType.PinCategory="materialinput",Direction="EGPD_Input",LinkedTo=())
End Object`,
  },
];
